### ISSUE TITLE
добавить правила из первого задания

### ISSUE THREAD

**Issue by 3dSpace116** [sergeywhite86/team_work#13]
Добить логику для "Сумма пополнений по всем продуктам типа DEBIT больше или равна 50 000 ₽ ИЛИ Сумма пополнений по всем продуктам типа SAVING больше или равна 50 000 ₽."

**Comment by 3dSpace116** [comment]
Сделано
https://github.com/sergeywhite86/team_work/tree/feature/NewRuleAdded

**Comment by 3dSpace116** [comment]
@sergeywhite86, необходимо проверить и забрать код в главную ветку develop

**Comment by sergeywhite86** [comment]
Сделал pr и добавил в develop
